# Generated by Django 5.0.1 on 2025-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stype', models.CharField(choices=[('Technical Support', 'Technical Support'), ('Billing & Account Support', 'Billing & Account Support'), ('Product/Service Request', 'Product/Service Request'), ('General Queries', 'General Queries')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='request/')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Not Resolved', 'Not Resolved')], default='In Progress', max_length=100)),
            ],
        ),
    ]
