# Generated by Django 5.1.6 on 2025-02-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='comment',
            field=models.CharField(default='No Comments', max_length=100),
        ),
    ]
